### ISSUE TITLE
Crash due try to call dismiss() on 7.1.2 SDK version

### ISSUE THREAD

**Issue by beshur** [usabilla/usabilla-u4a-react-native#144]
Reposted from https://github.com/usabilla/usabilla-u4a-android-sdk/issues/235

For presenting form we use:
1) `usabilla.setCustomVariables(options)`
2) `usabilla.loadFeedbackForm(USABILLA_NATIVE_FORM_ID)`
3) `usabilla.setFormDidClose(noop)`

for dismiss form we use:
1) `usabilla.dismiss()`

React Native "0.64.1"
usabilla-react-native is "0.13.1" 

We found a crash trying to call dismiss():
```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.stop(ReleaseTelemetryRecorder.kt:30)
at com.usabilla.sdk.ubform.telemetry.ReleaseTelemetryRecorder.startAndStop(ReleaseTelemetryRecorder.kt:23)
at com.usabilla.sdk.ubform.UsabillaInternal.dismiss(UsabillaInternal.kt:355)
at com.usabilla.sdk.ubform.Usabilla.dismiss(Usabilla.kt:147)
at com.usabilla.reactnative.ubform.UsabillaBridge.dismiss(UsabillaBridge.java:222)
at java.lang.reflect.Method.invoke(Method.java)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loop(Looper.java:224)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
at java.lang.Thread.run(Thread.java:919)
```
This crash happened on 7.1.2 version SDK.

One more crash with the iOS application when try to call dismiss():

```
Main Thread Checker: UI API called on a background thread: -[UIViewController childViewControllers]
PID: 12979, TID: 434586, Thread name: (none), Queue name: com.facebook.react.UsabillaBridgeQueue, QoS: 0
Backtrace:
4 x-bees 0x0000000108d0a16f -[RNNBottomTabsController selectedViewController] + 95
5 x-bees 0x0000000108d09b84 -[RNNBottomTabsController getCurrentChild] + 36
6 x-bees 0x0000000108d63215 -[UIViewController(LayoutProtocol) resolveOptions] + 69
7 x-bees 0x0000000108d07573 -[RNNBasePresenter getOrientation] + 67
8 x-bees 0x0000000108d0b063 -[RNNBottomTabsController supportedInterfaceOrientations] + 67
9 UIKitCore 0x00007fff23f7edc4 -[UIViewController __supportedInterfaceOrientations] + 746
10 UIKitCore 0x00007fff23f6ea7b -[UIViewController _preferredInterfaceOrientationGivenCurrentOrientation:] + 114
11 UIKitCore 0x00007fff23f7e834 -[UIViewController _preferredInterfaceOrientationForPresentationInWindow:fromInterfaceOrientation:] + 595
12 UIKitCore 0x00007fff23e459ba -[_UIFullscreenPresentationController _adjustOrientationIfNecessaryInWindow:forViewController:preservingViewController:] + 532
13 UIKitCore 0x00007fff23e3af17 -[UIPresentationController _dismissWithAnimationController:interactionController:target:didEndSelector:] + 544
14 UIKitCore 0x00007fff23f79e38 -[UIViewController _dismissViewControllerWithAnimationController:interactionController:completion:] + 510
15 UIKitCore 0x00007fff23f78fe0 -[UIViewController _dismissViewControllerWithTransition:from:completion:] + 1699
16 UIKitCore 0x00007fff23f78720 -[UIViewController dismissViewControllerWithTransition:completion:] + 2966
17 UIKit 0x0000000111508325 -[UIViewControllerAccessibility dismissViewControllerWithTransition:completion:] + 556
18 UIKitCore 0x00007fff23f78084 -[UIViewController dismissViewControllerWithTransition:completion:] + 1274
19 UIKit 0x0000000111508365 -[UIViewControllerAccessibility dismissViewControllerWithTransition:completion:] + 620
20 UIKitCore 0x00007fff23f77990 -[UIViewController performCoordinatedPresentOrDismiss:animated:] + 519
21 UIKitCore 0x00007fff23f7a915 -[UIViewController dismissViewControllerAnimated:completion:] + 126
22 UIKit 0x0000000111507eb4 -[UIViewControllerAccessibility dismissViewControllerAnimated:completion:] + 112
23 Usabilla 0x000000010cffb6e4 $s8UsabillaAAC7dismissSbyFZ + 84
24 x-bees 0x00000001097436eb $s21usabilla_react_native14UsabillaBridgeC7dismissyyF + 43
25 x-bees 0x000000010974372b $s21usabilla_react_native14UsabillaBridgeC7dismissyyFTo + 43
26 CoreFoundation 0x00007fff204282fc invoking + 140
27 CoreFoundation 0x00007fff204257b6 -[NSInvocation invoke] + 303
28 CoreFoundation 0x00007fff20425a47 -[NSInvocation invokeWithTarget:] + 70
29 x-bees 0x0000000108bf5004 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2660
30 x-bees 0x0000000108bf91ae _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 814
31 x-bees 0x0000000108bf8c76 _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 134
32 x-bees 0x0000000108bf8bdc ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 28
33 libdispatch.dylib 0x000000010ee727ec _dispatch_call_block_and_release + 12
34 libdispatch.dylib 2021-04-07 17:47:00.322568+0300 x-bees[12979:434586] [reports] Main Thread Checker: UI API called on a background thread: -[UIViewController childViewControllers]

NSInternalInconsistencyException Usabilla.PageViewController
Call must be made on main thread
```

**Comment by xanderwernecke** [comment]
Hi Beshur,


Thank you for reaching out, I'm happy to help!

I'd like to just confirm if you're experiencing this issue on android, iOS or on both? 

I'm looking forward to your response.


Kind Regards,

Xander Wernecke

**Comment by beshur** [comment]
Hello.

The crash happens on iOS

**Comment by xanderwernecke** [comment]
Hi @beshur  . Thank you for your patience on this case. 

Our Developer's took a look at this and have done some testing around this, however, were unable to reproduce this issue. Are you still experiencing this crash? 

I'm looking forward to your response!

Kind Regards,
Xander

**Comment by xanderwernecke** [comment]
This issue seems to have grown stale and as a result, we will close this ticket for now. Please feel free to open it again if you experience this issue again / continue to experience this issue. 

Kind Regards,

Xander
