### ISSUE TITLE
Android - Could not invoke UsabillaBridge.initialize

### ISSUE THREAD

**Issue by orel91** [usabilla/usabilla-u4a-react-native#164]
Hi,

We encounter a crash of our app when calling the usabilla.initialize function in our React Native code.

**Platform**: Android
**SDK**: v0.15.1
**Device & Device OS version**: Android 5.1.1
**Steps to reproduce**: Initialize usabilla in the code and launch the app
**Stack Trace**:
```
Fatal Exception: java.lang.RuntimeException: Could not invoke UsabillaBridge.initialize
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:145)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:818)
```

We are using React Native v0.64.1 and the SDK is working fine on newer models (Android 9 for example).

Can you please look into this?

Thank you and kind regards

**Comment by orel91** [comment]
Hello @stodorovicc, any news on this bug?

**Comment by stodorovicc** [comment]
Hi @orel91 , no news just yet on this bug unfortunately. I will get back to you as soon as our SDK team looks into this. 

Kind Regards,
Slobodan

**Comment by spylefkaditis-worldremit** [comment]
Is there any update on this? We're experiencing the same issue. 
We're on 
```
"react-native": "0.66.4",
"usabilla-react-native": "0.15.1",
```

**Comment by stodorovicc** [comment]
Hi @spylefkaditis-worldremit & @orel91 ,

Would you be able to update to latest react-native version and check if this issue persists?

Thanks in advance,
Slobodan

**Comment by stodorovicc** [comment]
Hi @orel91 & @spylefkaditis-worldremit,

I will close this issue since there was no reply. Feel free to open another one if this happens again.

Kind regards,
Slobodan
