### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: No definition found for a

### ISSUE THREAD

**Issue by WRiferreiro** [usabilla/usabilla-u4a-react-native#181]
Hello,

We've been getting hundreds of crashes with the following stack trace:

`Fatal Exception: java.lang.IllegalStateException: No definition found for a
       at com.usabilla.sdk.ubform.di.Component.getProvider(Component.kt:21)
       at com.usabilla.sdk.ubform.di.Component.get(Component.kt:13)
       at com.usabilla.sdk.ubform.di.Component.access$get(Component.kt:5)
       at com.usabilla.sdk.ubform.di.Component.get(Component.java:11)
       at com.usabilla.sdk.ubform.UsabillaInternal$special$$inlined$inject$4.invoke(Component.kt:37)
       at com.usabilla.sdk.ubform.di.Injected.getValue(Component.kt:34)
       at com.usabilla.sdk.ubform.UsabillaInternal.<clinit>(UsabillaInternal.kt:170)
       at com.usabilla.sdk.ubform.UsabillaInternal.access$getFormCloseIntentFilter$p(UsabillaInternal.kt:87)
       at com.usabilla.sdk.ubform.UsabillaInternal$sendEvent$1.invoke(UsabillaInternal.kt:474)
       at com.usabilla.sdk.ubform.UsabillaInternal$sendEvent$1.invoke(UsabillaInternal.kt:454)
       at com.usabilla.sdk.ubform.telemetry.UbTelemetryRecorder.start(UbTelemetryRecorder.kt:18)
       at com.usabilla.sdk.ubform.UsabillaInternal.sendEvent(UsabillaInternal.kt:454)
       at com.usabilla.sdk.ubform.Usabilla$sendEvent$1.invokeSuspend(Usabilla.kt:158)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

Looks like the issue is related to:
https://github.com/usabilla/usabilla-u4a-android-sdk/issues/278
https://github.com/usabilla/usabilla-u4a-android-sdk/issues/271
https://github.com/usabilla/usabilla-u4a-android-sdk/issues/294

The proposed solution on https://github.com/usabilla/usabilla-u4a-android-sdk/issues/294 of waiting for `UsabillaReadyCallback` is not possible since the react native implementation is not exposing the callback. We are rolling a fix by patching the package, but would be good to know if you are also planning on exposing this functionality.

Thanks

**Comment by terry-davies** [comment]
Facing the same issue. Is the issue being looked into and if so any ETA on a fix? Wary the issue is a few months old with no activity
