### ISSUE TITLE
Please fix the Null pointer exception crashes 

### ISSUE THREAD

**Issue by shivamarujolla** [usabilla/usabilla-u4a-react-native#205]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.HashMap com.facebook.react.bridge.ReadableMap.toHashMap()' on a null object reference
       at com.usabilla.reactnative.ubform.UsabillaBridge.setCustomVariables(UsabillaBridge.java:179)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
       at java.lang.Thread.run(Thread.java:920)

**Comment by lennardtastic** [comment]
Hi @shivamarujolla , Could you maybe share some additional information about your setup. Specifically, what version you are using and how you are setting the custom variables.

**Comment by emulroy9** [comment]
Thank you for your issue submission.

On December 1, we will be are closing out the issues tabs on the Usabilla GitHub repos. We will continue supporting the apps/SDKs via our Help Center and support team. Information on how to contact support will be provided in the readme sections of the repos. By consolidating our contact channels, our team can monitor and reply more efficiently.

If the issue you have reached out about persists, please send us an email at [support@usabilla.com](mailto:support@usabilla.com). Please include all details provided here in your email, along with any other details that may be helpful.

-GetFeedback Digital Team
